/**
 * NGUỒN DUY NHẤT cho toàn bộ chữ hiển thị (tiếng Việt) của ứng dụng.
 * Muốn đổi text ở bất cứ đâu → chỉ sửa tại file này.
 * Chuỗi có chèn biến được khai báo dưới dạng hàm: vd t.menu.confirmDelete('Cơm gà').
 */
export const t = {
  app: {
    name: 'Đặt Cơm Trưa',
    loading: 'Đang tải…',
  },

  actions: {
    cancel: 'Huỷ',
    save: 'Lưu',
    add: 'Thêm',
    delete: 'Xoá',
    saving: 'Đang lưu…',
    processing: 'Đang xử lý…',
    edit: '✏️ Sửa',
    copy: '📋 Copy',
  },

  errors: {
    generic: 'Có lỗi xảy ra',
    save: 'Lỗi lưu',
    short: 'Lỗi',
    status: (code: number) => `Lỗi ${code}`,
  },

  role: {
    admin: 'Admin',
    member: 'Thành viên',
    adminIcon: '🔓',
    memberIcon: '👤',
  },

  topbar: {
    changePassword: 'Đổi mật khẩu',
    settings: 'Cài đặt',
    logout: 'Đăng xuất',
  },

  notif: {
    title: '🔔 Thông báo',
    empty: 'Chưa có thông báo nào.',
    markAllRead: 'Đánh dấu đã đọc',
  },

  login: {
    subtitleLogin: 'Đăng nhập để đăng ký suất ăn',
    subtitleRegister: 'Tạo tài khoản mới (quyền thành viên)',
    tabLogin: 'Đăng nhập',
    tabRegister: 'Đăng ký',
    fullName: 'Họ tên',
    fullNamePlaceholder: 'Nguyễn Anh Khoa',
    email: 'Email',
    emailPlaceholder: 'ban@email.com',
    password: 'Mật khẩu',
    passwordPlaceholder: '••••••',
    submitLogin: 'Đăng nhập',
    submitRegister: 'Tạo tài khoản',
  },

  tabs: {
    grid: 'Bảng tuần',
    menu: 'Thực đơn',
    pay: 'Thanh toán',
    stats: 'Thống kê',
    hist: 'Lịch sử',
  },

  dashboard: {
    noWeekTitle: 'Chưa có tuần nào đang mở.',
    noWeekAdmin: ' Vào tab Lịch sử để tạo tuần mới.',
    noWeekMember: ' Nhờ admin tạo tuần mới nhé.',
    weekChip: 'Tuần:',
    statUnitPrice: '🍚 Đơn giá / suất',
    statTotalServings: '🧮 Tổng số suất',
    statTotalMoney: '💰 Tổng tiền',
    statEating: '👥 Đang ăn',
  },

  grid: {
    title: 'Bảng đăng ký tuần',
    // hướng dẫn chi tiết cho nghiệp vụ mới (mix món + đồ uống + chỉ đặt hôm nay)
    guide: {
      title: '📖 Cách đặt cơm',
      order: (price: string) => `🍚 Chạm ô để đặt cơm (${price}/ngày).`,
      detail: (where: string) =>
        `🍱 Chạm ${where} để mở phiếu chi tiết — chọn món (mix nhiều món vẫn 1 suất) & thêm đồ uống (tính tiền riêng theo giá).`,
      whereMobile: 'tên thành viên',
      whereDesktop: 'ô đã đặt',
      today: (cutoff: string) => `⏰ Chỉ đặt cho HÔM NAY, trước ${cutoff} — không đặt trước cho ngày sau.`,
      cancel: '❌ Bỏ tick = huỷ cả ngày (cơm + món + nước).',
      colors: '🎨 Ô cam 🍚 = có cơm · ô xanh 🥤 = chỉ uống nước.',
      admin: '👑 Admin: đặt/sửa hộ mọi người, mọi ngày (kể cả ngày đã khoá).',
      member: '✏️ Bạn chỉ sửa được dòng của mình.',
    },
    locked: 'Đã khoá',
    colMember: 'Thành viên',
    colServings: 'Số suất',
    colMoney: 'Thành tiền',
    totalRow: 'TỔNG CỘNG',
    autoSave: 'Tự động lưu khi tích',
    exportBtn: '📊 Xuất Excel',
    exported: 'Đã xuất Excel (CSV)',
    csv: { no: 'STT', name: 'Tên', total: 'TỔNG' },
    // mobile: chọn ngày → list thành viên
    pickDay: 'Chọn ngày',
    dayTotal: (n: number) => `${n} suất`,
    noEatersDay: 'Chưa ai đăng ký ngày này.',
    eatingDay: (n: number) => `${n} người ăn`,
    // phiếu chi tiết 1 ngày (mix món + đồ uống)
    detail: {
      eat: 'Ăn cơm',
      eatPrice: (price: string) => `1 suất • ${price}`,
      foodSection: 'Món ăn (mix nhiều món vẫn 1 suất)',
      foodEnableHint: 'Bật "Ăn cơm" để chọn món.',
      drinkSection: 'Đồ uống (tính tiền riêng)',
      riceLabel: 'Cơm',
      drinkLabel: 'Nước',
      totalLabel: 'Tổng',
      lockedView: '🔒 Ngày này đã khoá — chỉ xem, không sửa.',
      noFood: 'Chưa chọn món.',
      noDrink: 'Chưa có đồ uống.',
    },
  },

  menu: {
    title: 'Thực đơn',
    addBtn: '＋ Thêm món',
    emptyIcon: '🍽️',
    empty: 'Chưa có món nào.',
    emptyHintAdmin: ' Bấm ＋ Thêm món.',
    confirmDelete: (name: string) => `Xoá món "${name}"?`,
    deleted: 'Đã xoá món',
    modalEdit: 'Sửa món',
    modalCreate: 'Thêm món',
    fieldEmoji: 'Biểu tượng',
    fieldName: 'Tên món',
    namePlaceholder: 'VD: Cơm gà',
    fieldDesc: 'Mô tả',
    descPlaceholder: 'Ngắn gọn',
    fieldPrice: 'Giá (đ)',
    fieldCategory: 'Loại',
    catMain: '🍱 Món ăn',
    catDrink: '🥤 Đồ uống',
    foodSection: '🍱 Món ăn',
    drinkSection: '🥤 Đồ uống',
    sectionCount: (n: number) => `${n} món`,
    nameRequired: 'Nhập tên món',
    saved: 'Đã lưu món',
    added: 'Đã thêm món',
  },

  payment: {
    title: 'Thanh toán',
    accountHolder: 'Chủ tài khoản',
    bank: 'Ngân hàng',
    accountNumber: 'Số tài khoản',
    copied: 'Đã copy số tài khoản',
    memberHintLead: '🔎 Chạm tên để mở QR ',
    memberHintBold: 'đã điền sẵn số tiền',
    memberHintTail: ' của từng người.',
    noEaters: 'Chưa có ai đăng ký ăn.',
    servingsAmount: (servings: number, money: string) => `${servings} suất • ${money}`,
    qrInfoWeek: (label: string) => `Com trua ${label}`,
    qrInfoMember: (name: string, week: string) => `${name} - ${week}`,
    modalTitle: (name: string) => `Thanh toán · ${name}`,
    amountToTransfer: 'Số tiền cần chuyển',
    servingsTimesPrice: (servings: number, price: string) => `${servings} suất × ${price}`,
    // breakdown minh bạch cơm + nước
    breakdownRice: (servings: number) => `Cơm (${servings} suất)`,
    breakdownDrink: 'Đồ uống',
    breakdownTotal: 'Tổng cộng',
    includesDrinks: (money: string) => `gồm nước ${money}`,
    drinkDetail: (name: string, qty: number) => `${name} ×${qty}`,
    transferNote: 'Nội dung CK',
    // trạng thái công nợ + luồng báo/xác nhận
    status: { UNPAID: 'Chưa trả', PENDING: 'Chờ xác nhận', PAID: 'Đã thanh toán' },
    reportBtn: '📤 Tôi đã chuyển khoản',
    reportCancel: '↩️ Huỷ báo',
    reportWaiting: '⏳ Đã gửi — chờ admin xác nhận',
    paidDone: '✅ Đã thanh toán — cảm ơn bạn!',
    confirmBtn: '✅ Xác nhận đã nhận',
    rejectBtn: '↩️ Chưa nhận',
    reportedToast: 'Đã báo chuyển khoản, chờ admin xác nhận',
    reportCancelledToast: 'Đã huỷ báo',
    confirmedToast: 'Đã xác nhận thanh toán',
    rejectedToast: 'Đã chuyển về "Chưa trả"',
    reportedAt: (time: string) => `Báo lúc ${time}`,
    paidAt: (time: string) => `Xác nhận lúc ${time}`,
    pendingTab: (n: number) => `${n} người chờ xác nhận`,
    unmark: '↩️ Bỏ đánh dấu',
    markPaid: '✅ Đã thanh toán',
    unmarked: 'Đã bỏ đánh dấu',
    marked: 'Đã đánh dấu thanh toán',
    editTitle: 'Thông tin thanh toán',
    groupName: 'Tên nhóm',
    accountHolderNoAccent: 'Chủ tài khoản (không dấu)',
    updated: 'Đã cập nhật thanh toán',
  },

  stats: {
    byMember: 'Suất theo thành viên',
    noData: 'Chưa có dữ liệu',
    byDay: 'Suất theo ngày',
    trend: 'Xu hướng các tuần',
  },

  history: {
    title: 'Lịch sử các tuần',
    newBtn: '＋ Tuần mới',
    empty: 'Chưa có tuần nào.',
    active: 'Đang mở',
    meta: (servings: number, total: string, members: number, unitPrice: string) =>
      `${servings} suất • ${total} • ${members} người • ${unitPrice}/suất`,
    confirmDelete: (label: string) => `Xoá tuần "${label}"? Mọi đăng ký của tuần này sẽ mất.`,
    deleted: 'Đã xoá tuần',
    viewBtn: 'Xem',
    viewOnlyNote: '🔒 Tuần đã đóng — chỉ xem, không sửa.',
    hint: '🆕 "Tuần mới" tạo một tuần trống và đặt làm tuần hiện hành (giữ nguyên thành viên). Tuần cũ vẫn lưu ở đây.',
    modalTitle: 'Tạo tuần mới',
    fieldStartDate: 'Ngày bắt đầu (Thứ 2)',
    startDateHint: 'Dùng để khoá tick theo ngày & giờ chốt 10:21.',
    fieldLabel: 'Nhãn tuần',
    labelPlaceholder: 'VD: 22/6/2026 - 27/6/2026',
    fieldUnitPrice: 'Đơn giá / suất (đ)',
    labelRequired: 'Nhập nhãn tuần',
    created: 'Đã tạo tuần mới',
    createBtn: 'Tạo & kích hoạt',
  },

  settings: {
    title: '⚙️ Cài đặt (Admin)',
    currentWeek: 'Tuần hiện hành',
    fieldLabel: 'Nhãn tuần',
    fieldUnitPrice: 'Đơn giá / suất (đ)',
    saveWeek: 'Lưu tuần',
    savedWeek: 'Đã lưu tuần',
    members: (n: number) => `Thành viên (${n})`,
    locked: '(khoá)',
    changeRole: 'Đổi quyền',
    lock: 'Khoá',
    unlock: 'Mở khoá',
    confirmRemove: (name: string) => `Xoá thành viên "${name}"?`,
    removed: 'Đã xoá',
    roleChanged: (name: string, role: string) => `${name} → ${role}`,
  },

  password: {
    title: '🔑 Đổi mật khẩu',
    current: 'Mật khẩu hiện tại',
    new: 'Mật khẩu mới',
    tooShort: (min: number) => `Mật khẩu mới tối thiểu ${min} ký tự`,
    changed: 'Đổi mật khẩu thành công',
    submit: 'Đổi mật khẩu',
  },
} as const;
